[package]
name = "cli"
version = "0.0.0"
authors = ["Marvin Countryman <me@maar.vin>"]
edition = "2018"

[dependencies]
opencv = "0.34.0"
actix-web = "2.0"
actix-rt = "1.0"
actix-files = "0.2.1"
actix-web-actors = "2.0.0"
serde = "1.0.106"
serde_json = "1.0.51"
futures = "0.3.4"